name: nia_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  flutter_vector_icons: ^0.2.1
  http: ^0.12.0+4
  grouped_buttons: ^1.0.4
  auto_size_text: ^2.1.0
  flutter_secure_storage: ^3.3.1+1
  shared_preferences: ^0.5.4+8
  timeago: ^2.0.25
  flappy_search_bar: ^1.7.2
  pull_to_refresh: ^1.5.7
  cached_network_image: ^2.0.0-rc
  vcard: ^0.1.0
  flutter_mailer: ^0.4.2

  path_provider: ^1.6.0
  permission_handler: ^4.2.0+hotfix.3
  datetime_picker_formfield: ^1.0.0
  rflutter_alert:
  flutter_svg:
  hooks_riverpod: ^0.12.4
  flutter_hooks: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - assets/
